from utils.micro import *

args={
"datasets": Monu_Seg,
"gpu": GPU.GPU6,
"batchsize": BATCHSIZE8,
"imagesize": SIZE256,
"log": "log",
"seed": SEED,
"epoch": EPOCH,
"in_channels": INCHANNELRGB,
"embedding_dim": EMBEDDINGDIM.EMBEDDING_DIM_MIDDLE,
"time": TIMESTEP,
"lr": LR,
"ti": TI,
"esp": ESP,
"checkpoint_pth": CHECKPONITPATH,
"kernel_size": KERNEL3,
"freeze":FREEZE_Y,
"freeze_s":FREEZE_N,
"a_s": A_S_A,
"align": [0,0,0,1],
"opt":OPT_ADAM,
"lr":LR_RLROP,
"patience":30,
"resume":RESUME_N,
"resume_s":RESUME_N,
"model_type_s":SPIKE_MODEL,
"model_type_a":ANN_MODEL,
"weight_init_mode":INIT_KAIMING,
"bn_init_mode":BN_INIT_DEFAULT,
"proportion":DATASET_PROPORTION
}